baseURL = "https://epe105.github.io/blog/"
title = "Manny's Technology Blog"
theme = "hugo_theme_robust"

googleAnalytics = "UA-XXXXXXXX-XX" # Optional
disqusShortname = "mannytechblog"

[params]
  description = " This blog is about my love and journey in technology I work with on a daily basis."
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/profile.jpg"
  name = "Manny Evangelista"
  description = "<p>I am a father, a husband, and a aspiring techie.</p>"
  #facebook = "https://www.facebook.com/daisuke.tsuji.735"
  twitter = "https://twitter.com/Manny_PSU"
  github = "https://github.com/epe105/"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.
